#############################################################################
# Makefile for building: stt1.app/Contents/MacOS/stt1
# Generated by qmake (3.1) (Qt 5.9.7)
# Project:  stt1.pro
# Template: app
# Command: /Users/hongseunghyun/opt/anaconda3/bin/qmake -o project.pbxproj stt1.pro -spec macx-xcode
#############################################################################

MAKEFILE      = project.pbxproj

MOC       = /Users/hongseunghyun/opt/anaconda3/bin/moc
UIC       = 
LEX       = flex
LEXFLAGS  = 
YACC      = yacc
YACCFLAGS = -d
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
INCPATH       = -I. -I../../../opt/anaconda3/include/qt -I../../../opt/anaconda3/include/qt/QtQuick -I../../../opt/anaconda3/include/qt/QtGui -I../../../opt/anaconda3/include/qt/QtQml -I../../../opt/anaconda3/include/qt/QtNetwork -I../../../opt/anaconda3/include/qt/QtCore -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../../opt/anaconda3/mkspecs/macx-clang
DEL_FILE  = rm -f
MOVE      = mv -f

preprocess: compilers
clean preprocess_clean: compiler_clean

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compilers: qrc_qml.cpp moc_predefs.h
compiler_rcc_make_all: qrc_qml.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp
qrc_qml.cpp: qml.qrc \
		../../../opt/anaconda3/bin/rcc \
		PageSet.qml \
		PageDessert.qml \
		PageRecommend.qml \
		PageSearch.qml \
		PageBurger.qml \
		PageChicken.qml \
		main.qml \
		PageDrink.qml \
		images/microphone1.gif \
		images/mic1.gif \
		images/1.png \
		images/logo.png \
		images/next.png \
		images/logo2.png \
		images/back.png \
		images/microphone2.png \
		images/microphone1.png \
		images/menu/set/AZBurgerSet.jpg \
		images/menu/set/WagyuEdition2Set.jpg \
		images/menu/set/ClassicCheeseBurgerSet.jpg \
		images/menu/set/HanwooCouplePack.jpg \
		images/menu/set/BigBulgogiSet.jpg \
		images/menu/set/HanwooBulgogiSet.jpg \
		images/menu/set/MozzarellaInTheBurgerBaconSet.jpg \
		images/menu/set/ShrimpBurgerSet.jpg \
		images/menu/set/DoubleX2Set.jpg \
		images/menu/set/HotCrispyChickenBurgerSet.jpg \
		images/menu/set/TeriBurgerSet.jpg \
		images/menu/set/HanwooPremiumPack.jpg \
		images/menu/set/TREXBurgerSet.jpg \
		images/menu/set/HanwooBulgogiCombo.jpg \
		images/menu/set/BulgogiBurgerSet.jpg \
		images/menu/set/ChickenBurgerSet.jpg \
		images/menu/drink/IcedTea.jpg \
		images/menu/drink/MilkShakeStrawberry.jpg \
		images/menu/drink/ColaR.jpg \
		images/menu/drink/HotChoco.png \
		images/menu/drink/IceAmericano.jpg \
		images/menu/drink/IceCaffeLatte.jpg \
		images/menu/drink/MilkShakeVanilla.jpg \
		images/menu/drink/MilkShakeChoco.jpg \
		images/menu/drink/CafeLatte.jpg \
		images/menu/drink/CiderR.jpg \
		images/menu/drink/OrangeJuice.jpg \
		images/menu/drink/IceAmericanoL.jpg \
		images/menu/drink/Americano.jpg \
		images/menu/drink/Lemonade.jpg \
		images/menu/drink/Milk.jpg \
		images/menu/chicken/FriedChicken.jpg \
		images/menu/chicken/HalfPack.jpg \
		images/menu/chicken/LeanMeatHalfPack.jpg \
		images/menu/chicken/FamilyPack.jpg \
		images/menu/chicken/FireWing2.jpg \
		images/menu/chicken/ChickenFillet4.jpg \
		images/menu/chicken/FullPack.jpg \
		images/menu/chicken/LeanMeatFullPack.jpg \
		images/menu/chicken/ChickenFillet2.jpg \
		images/menu/chicken/FireWing4.jpg \
		images/menu/dessert/StrawberryTornado.jpg \
		images/menu/dessert/ShakeShakeCheese.jpg \
		images/menu/dessert/CornSalad.jpg \
		images/menu/dessert/CheeseStickOriginal.jpg \
		images/menu/dessert/ShakeShakeChilly.jpg \
		images/menu/dessert/Potato.jpg \
		images/menu/dessert/ShakeShakeOnion.jpg \
		images/menu/dessert/SquidRing.png \
		images/menu/dessert/SundayStrawberry.jpg \
		images/menu/dessert/JipieS.jpg \
		images/menu/dessert/JipieHabaneroL.jpg \
		images/menu/dessert/LongCheeseStick.jpg \
		images/menu/dessert/SeasonedPotato.jpg \
		images/menu/dessert/ChocoCookieTornado.jpg \
		images/menu/dessert/GreenTeaTornado.jpg \
		images/menu/dessert/ChickenNugget.jpg \
		images/menu/dessert/SoftCone.jpg \
		images/menu/burger/Teri.jpg \
		images/menu/burger/WagyuEdition2.jpg \
		images/menu/burger/DoubleX2.jpg \
		images/menu/burger/AZBurger.jpg \
		images/menu/burger/ChickenBurger.jpg \
		images/menu/burger/BigBulgogi.jpg \
		images/menu/burger/HanwooBulgogi.jpg \
		images/menu/burger/MozzarellaBacon.jpg \
		images/menu/burger/RiaMiracle.jpg \
		images/menu/burger/Bulgogi.jpg \
		images/menu/burger/ClassicCheese.jpg \
		images/menu/burger/Shrimp.jpg \
		images/menu/burger/TREX.jpg \
		images/menu/burger/HotCrispyChicken.jpg
	/Users/hongseunghyun/opt/anaconda3/bin/rcc -name qml qml.qrc -o qrc_qml.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../../opt/anaconda3/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h ../../../opt/anaconda3/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean 

